version: '3'
services:
    dj_backend:
      build: 
        context: ./build/backend
        dockerfile: build_backend
      security_opt:
        - seccomp:unconfined
      networks:
        - internalNetwork
      volumes:
        - "./bin/backend/:/app/webserver/"

    react_frontend:
      build:
        context: ./
        dockerfile: ./build/frontend/build_frontend
      security_opt:
        - seccomp:unconfined
      ports:
        - "80:80"
      networks:
        - internalNetwork
      volumes:
        - "./bin/frontend/:/app/react/frontend"
      depends_on:
        - dj_backend

    nginx_server:
      build:
        context: ./
        dockerfile: ./build/nginx/build_nginx
      ports:
        - 8000:8000
      depends_on:
        - dj_backend
      networks:
        - internalNetwork

    rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
        - 5672:5672
        - 15672:15672
          #      volumes:
          #        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
          #        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      networks:
        - internalNetwork
    worker:
      build:
        context: ./build/celery_worker
        dockerfile: build_worker
      depends_on:
        - "rabbitmq"
      volumes:
        - "./bin/celery_worker:/worker/"
      networks:
        - internalNetwork
networks:
  internalNetwork:
